# Generated by Django 5.1.5 on 2025-02-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='hotelimages',
            name='amenity',
        ),
    ]
