# Generated by Django 5.1.5 on 2025-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_remove_amenities_amenity_remove_hotelimages_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(),
        ),
    ]
